// Service to handle exporting resume analysis results
export const exportResumeAnalysis = async (resumeData, analysisResults, format = 'pdf') => {
  try {
    if (format === 'pdf') {
      // In a real implementation, this would generate a PDF
      // For now, we'll simulate the export functionality
      return await exportToPdf(resumeData, analysisResults);
    } else if (format === 'json') {
      return exportToJson(resumeData, analysisResults);
    } else if (format === 'docx') {
      return await exportToDocx(resumeData, analysisResults);
    } else {
      throw new Error(`Unsupported format: ${format}`);
    }
  } catch (error) {
    console.error('Error exporting resume analysis:', error);
    throw error;
  }
};

// Export to PDF format via Print
const exportToPdf = async (resumeData, analysisResults) => {
  // Use browser's built-in Print functionality which allows Save as PDF
  const printWindow = window.open('', '_blank');

  if (!printWindow) {
    alert("Popup blocked! Please allow popups for this site to export the PDF.");
    return { success: false, message: 'Popup blocked' };
  }

  const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Resume Analysis Report - ${resumeData.fileName}</title>
      <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 0; padding: 40px; color: #333; }
        .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #eee; padding-bottom: 20px; }
        .score-circle { 
            width: 100px; height: 100px; border-radius: 50%; background: #10b981; 
            color: white; display: flex; align-items: center; justify-content: center; 
            font-size: 32px; font-weight: bold; margin: 0 auto 20px;
        }
        .section { margin: 30px 0; page-break-inside: avoid; }
        h3 { color: #10b981; border-bottom: 1px solid #ddd; padding-bottom: 8px; margin-bottom: 15px; }
        ul { padding-left: 20px; }
        li { margin-bottom: 8px; line-height: 1.5; }
        .stat-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; margin-bottom: 30px; }
        .stat-item { background: #f9f9f9; padding: 15px; border-radius: 8px; }
        .stat-label { font-size: 0.9em; color: #666; display: block; }
        .stat-value { font-size: 1.2em; font-weight: bold; color: #333; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Resume Analysis Report</h1>
        <h2>${resumeData.fileName}</h2>
        <div class="score-circle">${analysisResults?.overallScore || 0}%</div>
        <p>Generated by AI Resume Analyzer</p>
      </div>
      
      <div class="stat-grid">
         <div class="stat-item">
            <span class="stat-label">ATS Compatibility</span>
            <span class="stat-value">${analysisResults?.scores?.ats || 0}/30</span>
         </div>
         <div class="stat-item">
            <span class="stat-label">Keyword Alignment</span>
            <span class="stat-value">${analysisResults?.scores?.keyword || 0}/30</span>
         </div>
         <div class="stat-item">
            <span class="stat-label">Impact Factor</span>
            <span class="stat-value">${analysisResults?.scores?.content || 0}/20</span>
         </div>
         <div class="stat-item">
            <span class="stat-label">Role Relevance</span>
            <span class="stat-value">${analysisResults?.scores?.relevance || 0}/20</span>
         </div>
      </div>
      
      <div class="section">
        <h3>Analysis Summary</h3>
        <p>${analysisResults?.summary || 'Comprehensive analysis of resume strengths and weaknesses.'}</p>
      </div>
      
      <div class="section">
        <h3>Strengths</h3>
        <ul>
          ${(analysisResults?.strengths || []).map(strength => `<li>${strength}</li>`).join('')}
        </ul>
      </div>
      
      <div class="section">
        <h3>Areas for Improvement</h3>
        <ul>
          ${(analysisResults?.weaknesses || []).map(weakness => `<li>${weakness}</li>`).join('')}
        </ul>
      </div>
      
      <div class="section">
        <h3>Strategic Suggestions</h3>
        <ul>
          ${(analysisResults?.suggestions || []).map(suggestion => `<li>${suggestion}</li>`).join('')}
        </ul>
      </div>
      
      <script>
        window.onload = function() { window.print(); }
      </script>
    </body>
    </html>
  `;

  printWindow.document.write(htmlContent);
  printWindow.document.close();

  return { success: true, message: 'PDF Export dialog opened. Please choose "Save as PDF".' };
};

// Export to JSON format
const exportToJson = (resumeData, analysisResults) => {
  const exportData = {
    metadata: {
      fileName: resumeData.fileName,
      exportDate: new Date().toISOString(),
      fileSize: resumeData.fileSize
    },
    resumeData: resumeData,
    analysisResults: analysisResults
  };

  const jsonStr = JSON.stringify(exportData, null, 2);
  const blob = new Blob([jsonStr], { type: 'application/json' });
  const url = URL.createObjectURL(blob);

  // Trigger download
  const a = document.createElement('a');
  a.href = url;
  a.download = `resume-analysis-${resumeData.fileName.replace(/\.[^/.]+$/, '')}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);

  return { success: true, message: 'JSON exported successfully' };
};

// Export to DOCX format (simulated)
const exportToDocx = async (resumeData, analysisResults) => {
  // For a real implementation, you would use a library like docx
  // For now, we'll simulate the functionality with a text file

  const docContent = `RESUME ANALYSIS REPORT
===================

File: ${resumeData.fileName}
Date: ${new Date().toLocaleDateString()}

OVERALL SCORE: ${analysisResults?.overallScore || 0}/100

BREAKDOWN:
- ATS Compatibility: ${analysisResults?.scores?.ats || 0}/30
- Keyword Match: ${analysisResults?.scores?.keyword || 0}/30
- Content Quality: ${analysisResults?.scores?.content || 0}/20
- Role Relevance: ${analysisResults?.scores?.relevance || 0}/20

STRENGTHS:
${(analysisResults?.strengths || []).map(strength => `- ${strength}`).join('\n')}

AREAS FOR IMPROVEMENT:
${(analysisResults?.weaknesses || []).map(weakness => `- ${weakness}`).join('\n')}

SUGGESTIONS:
${(analysisResults?.suggestions || []).map(suggestion => `- ${suggestion}`).join('\n')}
`;

  const blob = new Blob([docContent], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);

  // Trigger download
  const a = document.createElement('a');
  a.href = url;
  a.download = `resume-analysis-${resumeData.fileName.replace(/\.[^/.]+$/, '')}.doc`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);

  return { success: true, message: 'DOCX exported successfully' };
};

// Export resume with suggested improvements
export const exportImprovedResume = async (originalResumeData, analysisResults) => {
  // This would generate an improved version of the resume based on analysis
  // For now, we'll just return the original with suggestions appended

  const improvedContent = {
    ...originalResumeData,
    improvements: {
      suggestions: analysisResults?.suggestions || [],
      targetedKeywords: analysisResults?.keywordMatches?.missing || [],
      recommendedSections: generateRecommendedSections(originalResumeData, analysisResults)
    }
  };

  const jsonStr = JSON.stringify(improvedContent, null, 2);
  const blob = new Blob([jsonStr], { type: 'application/json' });
  const url = URL.createObjectURL(blob);

  // Trigger download
  const a = document.createElement('a');
  a.href = url;
  a.download = `improved-resume-${originalResumeData.fileName.replace(/\.[^/.]+$/, '')}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);

  return { success: true, message: 'Improved resume exported successfully' };
};

// Generate recommended sections based on analysis
const generateRecommendedSections = (resumeData, analysisResults) => {
  const recommendations = [];

  // Add recommendations based on weaknesses
  if (analysisResults?.weaknesses) {
    analysisResults.weaknesses.forEach(weakness => {
      if (weakness.toLowerCase().includes('summary')) {
        recommendations.push({
          section: 'summary',
          recommendation: 'Consider rewriting your summary to be more compelling and specific to the target role'
        });
      } else if (weakness.toLowerCase().includes('experience')) {
        recommendations.push({
          section: 'experience',
          recommendation: 'Add more quantifiable achievements with specific metrics to your experience descriptions'
        });
      } else if (weakness.toLowerCase().includes('skills')) {
        recommendations.push({
          section: 'skills',
          recommendation: 'Review and update your skills section to include more relevant keywords from job descriptions'
        });
      }
    });
  }

  // Add recommendations based on missing keywords
  if (analysisResults?.keywordMatches?.missing) {
    recommendations.push({
      section: 'skills',
      recommendation: `Consider adding these missing keywords to improve ATS compatibility: ${analysisResults.keywordMatches.missing.slice(0, 5).join(', ')}`
    });
  }

  return recommendations;
};